[project]
name = "model"
version = "1.0.0"
description = "Solo model project template."
requires-python = ">=3.12,<3.13"
dependencies = [
    "scheme>=1.0.0,<2.0.0",
    "pydantic>=2,<3",
]

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["ipykernel>=6,<8"]
