[project]
name = "solo-model"
version = "0.1.0"
description = "Solo model project template."
requires-python = ">=3.12"
dependencies = [
    "scheme @ git+https://github.com/Genesis-Quant/solo-algo-scheme@b89655d85caac6ec3d369508e22f15ff34dbb5dd",
    "pydantic>=2,<3",
    "backtest @ git+https://github.com/Genesis-Quant/backtest@d6ea13caec7f049ac32b715486636f38fccfab79",
]

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["ipykernel>=6,<8"]
