[project]
name = "solo-execution"
version = "0.1.0"
description = "Solo execution project template."
requires-python = ">=3.12"
dependencies = [
    "scheme @ git+https://github.com/Genesis-Quant/solo-algo-scheme@82d94e21c0cfeca0794b3669b1aa1e50958dc50c",
    "pydantic>=2,<3",
    "backtest @ git+https://github.com/Genesis-Quant/backtest@d6ea13caec7f049ac32b715486636f38fccfab79",
]

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["ipykernel>=6,<8"]
